HW-01 ready
YaroslavKuzero/goit-nodejs-hw pull request #1
Opened 2020-09-02 14:25 UTC by YaroslavKuzero

2020-09-07 10:47 UTC, odykyi commented on contacts.js
> +    fs.writeFile(this.contactsPath, JSON.stringify(contactsList))
await

2020-09-07 10:48 UTC, odykyi requested changes
comments

2020-09-07 11:14 UTC, YaroslavKuzero commented on contacts.js
> +    fs.writeFile(this.contactsPath, JSON.stringify(contactsList))
Changed.

2020-09-07 11:18 UTC, YaroslavKuzero commented
> comments

Fixed

2020-09-08 10:40 UTC, odykyi approved these changes

2020-09-08 10:40 UTC, merged