ready hw-04
YaroslavKuzero/goit-nodejs-hw pull request #4
Opened 2020-10-03 17:39 UTC by YaroslavKuzero

2020-10-05 06:37 UTC, odykyi commented on api/auth/auth.controller.js
> +    const { id } = req.user
what happens when user will not send Authorization header to logout endpoint ?

id will undefined 



you should throw error before code line ```const user = await User.getUserById(id)```

2020-10-05 06:40 UTC, odykyi commented on api/contacts/contacts.router.js
> +contactsRouter.get('/:contactId', getContactById)
add verifyTokenMiddlware here

2020-10-05 06:42 UTC, odykyi commented on api/users/users.controller.js
> +    if (!user) {
you already have verified user in middleware

2020-10-05 06:42 UTC, odykyi requested changes
comments

2020-10-05 16:37 UTC, YaroslavKuzero commented on api/contacts/contacts.router.js
> +contactsRouter.get('/:contactId', getContactById)
added

2020-10-06 10:14 UTC, odykyi commented on api/contacts/contacts.model.js
> +    let options = {
const

2020-10-06 10:15 UTC, odykyi approved these changes

2020-10-06 10:16 UTC, merged