HW-06-ready
YaroslavKuzero/goit-nodejs-hw pull request #6
Opened 2020-10-15 12:36 UTC by YaroslavKuzero

2020-10-15 15:13 UTC, odykyi commented on api/auth/auth.controller.js
> +    sendEmail(newUser.email, verificationToken);
await

2020-10-15 15:14 UTC, odykyi commented on services/email.service.js
> +    from: 'yarikkuzero@gmail.com',
move from to config

2020-10-15 15:14 UTC, odykyi commented on services/email.service.js
> +    await sgMail.send(message).then(() => console.log('Email sent'))
remove then

2020-10-15 15:14 UTC, odykyi requested changes
comments

2020-10-16 08:31 UTC, odykyi commented on services/jwt.service.js
> +const KEY = process.env.KEY;
KEY - its implicit

use JWT_SECRET_KEY

2020-10-16 08:32 UTC, odykyi commented on services/config.js
>    hostURL: 'http://localhost:3000/',
remove async await  from functions createAvaURL, tempPath and createAvaDB

2020-10-16 08:32 UTC, odykyi commented on services/config.js
>    hostURL: 'http://localhost:3000/',
@YaroslavKuzero

2020-10-16 08:33 UTC, odykyi requested changes
comments

2020-10-16 09:20 UTC, odykyi commented on services/jwt.service.js
>    const token = await jwt.sign(payload, KEY);
use JWT_SECRET_KEY instead of KEY

2020-10-16 09:20 UTC, odykyi requested changes
comments

2020-10-16 10:19 UTC, YaroslavKuzero commented on services/jwt.service.js
>    const token = await jwt.sign(payload, KEY);
Sorry) Misprint

2020-10-16 11:54 UTC, odykyi approved these changes

2020-10-16 11:54 UTC, merged